# Generated by Django 5.2 on 2025-06-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('des', models.CharField(blank=True, max_length=45, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_money', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('interested', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('des', models.CharField(blank=True, max_length=45, null=True)),
                ('is_agreed', models.BooleanField(blank=True, null=True)),
                ('activity_id', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.activity')),
                ('applicant_id_a', models.ForeignKey(db_column='applicant_id_a', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user')),
            ],
            options={
                'db_table': 'application_activity',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='publisher_id_w',
            field=models.ForeignKey(db_column='publisher_id_w', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user'),
        ),
        migrations.CreateModel(
            name='Volntary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('des', models.CharField(blank=True, max_length=45, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_money', models.FloatField(blank=True, null=True)),
                ('publisher_id_v', models.ForeignKey(db_column='publisher_id_v', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user')),
            ],
            options={
                'db_table': 'volntary',
            },
        ),
        migrations.CreateModel(
            name='ApplicationVoluntary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('des', models.CharField(blank=True, max_length=45, null=True)),
                ('is_agreed', models.BooleanField(blank=True, null=True)),
                ('application_id_v', models.ForeignKey(db_column='application_id_v', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user')),
                ('volntary_id', models.ForeignKey(db_column='volntary_id', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.volntary')),
            ],
            options={
                'db_table': 'application_voluntary',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('des', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('hourly_pay', models.FloatField(blank=True, null=True)),
                ('is_long', models.BooleanField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('publisher_id_w', models.ForeignKey(db_column='publisher_id_w', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='ApplicationWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('des', models.CharField(blank=True, max_length=45, null=True)),
                ('is_agree', models.BooleanField(blank=True, null=True)),
                ('applicant_id_w', models.ForeignKey(db_column='applicant_id_w', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user')),
                ('work_id', models.ForeignKey(db_column='work_id', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.work')),
            ],
            options={
                'db_table': 'application_work',
            },
        ),
    ]
