# Generated by Django 5.2 on 2025-06-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elderlyserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationactivity',
            name='is_over',
            field=models.BooleanField(blank=True, null=True, verbose_name='申请是否结束'),
        ),
        migrations.AddField(
            model_name='applicationvoluntary',
            name='is_over',
            field=models.BooleanField(blank=True, null=True, verbose_name='申请是否结束'),
        ),
        migrations.AddField(
            model_name='applicationwork',
            name='is_over',
            field=models.BooleanField(blank=True, null=True, verbose_name='申请是否结束'),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(default=1, max_length=128, unique=True, verbose_name='微信小程序用户唯一标识id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='活动地址'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='des',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='社交活动ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='publisher_id_w',
            field=models.ForeignKey(db_column='publisher_id_w', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user', verbose_name='发布者ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_money',
            field=models.FloatField(blank=True, null=True, verbose_name='时间价值'),
        ),
        migrations.AlterField(
            model_name='applicationactivity',
            name='activity_id',
            field=models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.activity', verbose_name='活动ID'),
        ),
        migrations.AlterField(
            model_name='applicationactivity',
            name='applicant_id_a',
            field=models.ForeignKey(db_column='applicant_id_a', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user', verbose_name='申请人ID'),
        ),
        migrations.AlterField(
            model_name='applicationactivity',
            name='des',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='申请描述'),
        ),
        migrations.AlterField(
            model_name='applicationactivity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='活动申请ID'),
        ),
        migrations.AlterField(
            model_name='applicationactivity',
            name='is_agreed',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否同意'),
        ),
        migrations.AlterField(
            model_name='applicationvoluntary',
            name='application_id_v',
            field=models.ForeignKey(db_column='application_id_v', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user', verbose_name='申请人ID'),
        ),
        migrations.AlterField(
            model_name='applicationvoluntary',
            name='des',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='申请描述'),
        ),
        migrations.AlterField(
            model_name='applicationvoluntary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='志愿申请ID'),
        ),
        migrations.AlterField(
            model_name='applicationvoluntary',
            name='is_agreed',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否同意'),
        ),
        migrations.AlterField(
            model_name='applicationvoluntary',
            name='volntary_id',
            field=models.ForeignKey(db_column='volntary_id', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.volntary', verbose_name='志愿活动ID'),
        ),
        migrations.AlterField(
            model_name='applicationwork',
            name='applicant_id_w',
            field=models.ForeignKey(db_column='applicant_id_w', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user', verbose_name='申请人ID'),
        ),
        migrations.AlterField(
            model_name='applicationwork',
            name='des',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='申请描述'),
        ),
        migrations.AlterField(
            model_name='applicationwork',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='工作申请ID'),
        ),
        migrations.AlterField(
            model_name='applicationwork',
            name='is_agree',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否同意'),
        ),
        migrations.AlterField(
            model_name='applicationwork',
            name='work_id',
            field=models.ForeignKey(db_column='work_id', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.work', verbose_name='工作ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.IntegerField(blank=True, null=True, verbose_name='受教育程度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested',
            field=models.IntegerField(blank=True, null=True, verbose_name='兴趣领域'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='活动地址'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='des',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='志愿活动ID'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='publisher_id_v',
            field=models.ForeignKey(db_column='publisher_id_v', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user', verbose_name='发布者ID'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='volntary',
            name='time_money',
            field=models.FloatField(blank=True, null=True, verbose_name='时间价值'),
        ),
        migrations.AlterField(
            model_name='work',
            name='address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='工作地址'),
        ),
        migrations.AlterField(
            model_name='work',
            name='des',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='工作描述'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='hourly_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='时薪'),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='工作ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_long',
            field=models.BooleanField(blank=True, null=True, verbose_name='长期性'),
        ),
        migrations.AlterField(
            model_name='work',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='work',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publisher_id_w',
            field=models.ForeignKey(db_column='publisher_id_w', on_delete=django.db.models.deletion.DO_NOTHING, to='elderlyserver.user', verbose_name='发布者ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.IntegerField(blank=True, null=True, verbose_name='工作类型'),
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('rating', models.IntegerField(verbose_name='评论星级')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('commented_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='elderlyserver.user', verbose_name='被评论者ID')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to='elderlyserver.user', verbose_name='评论者ID')),
            ],
            options={
                'db_table': 'user_comment',
            },
        ),
    ]
