# Generated by Django 5.2 on 2025-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elderlyserver', '0003_user_have_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationwork',
            name='employer_confirmed',
            field=models.BooleanField(default=False, verbose_name='发布者确认'),
        ),
        migrations.AddField(
            model_name='applicationwork',
            name='worker_confirmed',
            field=models.BooleanField(default=False, verbose_name='工作者确认'),
        ),
    ]
